ARG BASE_TAG
FROM pizzafactory0contorno/piatto:${BASE_TAG}

RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - \
 && sudo apt update \
 && sudo apt install -y npm poppler-utils ghostscript \
 && sudo npm install -g @vivliostyle/cli
